// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuEZm0B34m3WeCZQOgyiEQhcU7AaT5_B8',
    appId: '1:1034968302272:web:bca0d6b2d753c8b1b7e325',
    messagingSenderId: '1034968302272',
    projectId: 'routelink-1428b',
    authDomain: 'routelink-1428b.firebaseapp.com',
    storageBucket: 'routelink-1428b.firebasestorage.app',
    measurementId: 'G-VVF5S5ZZQG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHLjkZe6080sk4Xz5mHMA5dc82_9bMoCA',
    appId: '1:1034968302272:android:790cbee40c82233fb7e325',
    messagingSenderId: '1034968302272',
    projectId: 'routelink-1428b',
    storageBucket: 'routelink-1428b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQxGCUSbZTpVATAHQJtDEwfZE5HKFJfGg',
    appId: '1:1034968302272:ios:3f4d28c4467303aab7e325',
    messagingSenderId: '1034968302272',
    projectId: 'routelink-1428b',
    storageBucket: 'routelink-1428b.firebasestorage.app',
    iosBundleId: 'com.example.routelink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQxGCUSbZTpVATAHQJtDEwfZE5HKFJfGg',
    appId: '1:1034968302272:ios:3f4d28c4467303aab7e325',
    messagingSenderId: '1034968302272',
    projectId: 'routelink-1428b',
    storageBucket: 'routelink-1428b.firebasestorage.app',
    iosBundleId: 'com.example.routelink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuEZm0B34m3WeCZQOgyiEQhcU7AaT5_B8',
    appId: '1:1034968302272:web:c5ea50033f7fdac8b7e325',
    messagingSenderId: '1034968302272',
    projectId: 'routelink-1428b',
    authDomain: 'routelink-1428b.firebaseapp.com',
    storageBucket: 'routelink-1428b.firebasestorage.app',
    measurementId: 'G-TKG3DPYHWZ',
  );
}
